sudo: required
services: 
 - docker

before_install:
  - docker build -t seitmagambet/docker-react -f Dockerfile.dev . 

script:
  - docker run seitmagambet/docker-react npm run test -- --coverage




